dist: trusty
language: generic

services:
    - docker

install:
    docker pull debian:stretch

script:
    docker run -v "$PWD:/workspace/nexsan-exporter" -w /workspace/nexsan-exporter debian:stretch './.travis-build.sh'
